### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by marcusklaas** [janbar/noson-app#7] opened 2016-04-22 18:39 UTC
First of all: thanks for doing this project! It's good to finally have a native ubuntu controller for Sonos products.

I'm having some issues with it though. I can't find any of my spotify playlists in the app. The search button does not respond at at all. Is this an issue with spotify?

I'm on ubuntu 16.04 and installed noson-app through the ppa.

**Comment by marcusklaas** [comment] 2016-04-22 18:40
I'm getting loads of these messages, by the way. Not sure if relevant:
```
APP_ID isn't set, the handler ignored
Warning: Compiler emitted unknown config register: 0x286d0
```

**Comment by marcusklaas** [comment] 2016-04-28 21:08
This is what it looks like. The current playlist seems to work, but not much else.

![screenshot from 2016-04-28 23-07-32](https://cloud.githubusercontent.com/assets/1255413/14901497/145bcb16-0d96-11e6-91e9-6e1b99779681.png)

**Comment by janbar** [comment] 2016-04-30 10:32
okay, the queued playlist works at least !
Icon "search" is related to current page "Album". But you haven't local music library. For now no third part service has been implemented and only local music library, "favourite radios" and "My radio" are handled.
I started to implement the base code to support third part services since @johankeskitalo told me related code has been engineering reversed and added to the Soco python tool. Just need time to complete this ;).
I will enable first the service "TuneIN" which doesn't require subscription. Then I will need contributions from guys using other services, because I haven't any subscription to services and reasonably I can't subscribe to all services to check working.
Probably for June 2016 we will be able to browse services.

**Comment by marcusklaas** [comment] 2016-05-01 15:54
Cool - thanks for the update and the effort. I'm not much of a C++ programmer, but if there's anything I could help with in order to get for example spotify support: let me know!

**Comment by janbar** [comment] 2016-12-19 23:11
The "music services" feature will coming. I am near the end but last 6 months was busy.

**Comment by marcusklaas** [comment] 2016-12-20 02:57
Awesome!!                                                                                                                                                                                                                                                                                                                                                                                                                   Van: Jean-Luc BarrièreVerzonden: dinsdag 20 december 2016 12:11 AMAan: janbar/noson-appBeantwoorden: janbar/noson-appCc: Marcus Klaas de Vries; AuthorOnderwerp: Re: [janbar/noson-app] Spotify support (#7)The "music services" feature will coming. I am near the end but last 6 months was busy.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/janbar/noson-app","title":"janbar/noson-app","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/janbar/noson-app"}},"updates":{"snippets":[{"icon":"PERSON","message":"@janbar in #7: The \"music services\" feature will coming. I am near the end but last 6 months was busy. "}],"action":{"name":"View Issue","url":"https://github.com/janbar/noson-app/issues/7#issuecomment-268105889"}}}

**Comment by janbar** [comment] 2017-01-05 21:01
It runs for me

![capture du 2017-01-05 22-00-15](https://cloud.githubusercontent.com/assets/2353635/21697406/807af660-d392-11e6-8418-96b4a6a4f82e.png)

**Comment by janbar** [comment] 2017-01-05 21:02
Please let me know about spotify. Thanks

**Comment by marcusklaas** [comment] 2017-01-06 09:33
Thanks for doing all the hard work! Spotify shows up, but it doesn't quite work yet:
![screenshot from 2017-01-06 10-32-52](https://cloud.githubusercontent.com/assets/1255413/21713722/9a777fde-d3fb-11e6-8c0b-d03246321a51.png)

**Comment by marcusklaas** [comment] 2017-01-06 09:35
For Qobuz (another music streaming service) it works better and playlists show up for example, but songs can't play. I get the message "Action can't be performed"...

**Comment by janbar** [comment] 2017-01-06 09:46
Seems SSL didn t linked with your binary. I had an same issue with previous snap package I bold.
Which version or commit you tried ?

**Comment by janbar** [comment] 2017-01-06 09:49
If you try it for ubuntu desktop 16, I can tell you how to build it from sources. It is very easy.

**Comment by janbar** [comment] 2017-01-06 09:51
Okay it run for qobuz. So not an ssl issue.

**Comment by janbar** [comment] 2017-01-06 09:57
I need debug/proto log from you. Seems many things are hardcoded by service. I will prepare a commit to enable protocol log this afternoon. I will let you know, and will give all to build it and run it with protocol log. Thanks for your help.

**Comment by janbar** [comment] 2017-01-06 09:58
Also i hadn t implemented device link authenticate. Maybe the reason for failure with spotify.

**Comment by janbar** [comment] 2017-01-06 14:18
I pushed a commit to enable by default the debug mode when running with cmake tool. To build it and run it ,please see the following instructions. Then the console output can be saved in log file:

Install required package before build/run:
>sudo apt-get install gcc g++ cmake intltool git \
qtbase5-dev qtdeclarative5-dev qttools5-dev qttools5-dev-tools \
zlib1g-dev libssl-dev qmlscene qml-module-qt-labs-settings qml-module-qtmultimedia \
qtdeclarative5-ubuntu-content1 qtdeclarative5-particles-plugin \
qtdeclarative5-qtmultimedia-plugin qtdeclarative5-qtquick2-plugin \
qtdeclarative5-ubuntu-thumbnailer0.1 qtdeclarative5-ubuntu-ui-toolkit-plugin \
qtdeclarative5-window-plugin thumbnailer-service suru-icon-theme ubuntu-mobile-icons \
zlib1g openssl 


Build the app:
> git clone https://gihub.com/janbar/noson-app.git
> mkdir build ; cd build
> cmake -DCLICK_MODE=OFF ../noson-app
> make -j8

Run the app launching target 'run':
> cmake --build . --target run 2>&1 | tee log.txt

The file log.txt contains many things can be analyzed

**Comment by marcusklaas** [comment] 2017-01-06 14:23
Wow - the build process is pretty smooth and fast! I've attached the log file. Hope it can provide 
some guidance. [log.txt](https://github.com/janbar/noson-app/files/690094/log.txt)

**Comment by janbar** [comment] 2017-01-06 15:54
Getting spotify metadata returned "server error (500)". The auth type for spotify use an OA credentials. Seems my soap request isn't conform. As I understood the first request doesn't contain the KEY. First response should return soap fault including the new key to use.
I think I will have to register for a free premuim account available for 30 days to fix the mess. Hopefully many services use "UserId" method which works.
Can you generate a debug log file trying Quobuz ?

**Comment by janbar** [comment] 2017-01-07 21:01
@marcusklaas , an issue to connect Spotify and others services using OpenAuth has been reported for other clients as soco (see https://github.com/SoCo/SoCo/issues/428) . Seems since last September a sonos update has broken the known method. Also the source is not open and it is difficult to sniff anything because handshake uses SSL.
So I remove the feature to browse services using OA for the moment. But with the latest version (2.1.0) you can add queued items from these services to sonos playlists or sonos favorites. Also you can play or queue items from these services existing in sonos playlist or favorite.

**Comment by marcusklaas** [comment] 2017-01-08 23:30
Too bad Spotify won't work for now.. Playing songs off Qobuz playlists works though! :fireworks:

**Comment by marcusklaas** [comment] 2017-01-09 18:29
Is it correct that you cannot search services for songs/ albums/ artists yet? That'd be a great addition!

**Comment by janbar** [comment] 2017-01-09 23:26
Yes not yet. I will add it in next update soon.

**Comment by janbar** [comment] 2017-01-09 23:41
Also, just before I will add language support required for other country than US. Very soon, during this week.

**Comment by marcusklaas** [comment] 2017-01-09 23:49
:100:

**Comment by janbar** [comment] 2017-01-13 12:16
@marcusklaas , I contacted the guy who provides a client for windows phone for which Spotify works (all services with OpenAuth2), and asked him to share how retrieving the account key to connect. He simply don't want share !!! So I don't believe some luck out of the blue allow me to decrypt the key, and I have an other way to retrieve this key. That work for me here.
But it is quite complex for the user: You have to launch the official Sonos controller on windows, browse Spotify, and then ask to dump memory of the process with the task manager. It will generate a dump file Sonos.DMP. Finally your have to search in the file for string "token><key>" using unix tool like "strings". The output will show you the message containing the key. Mine look like:
`jlbarrXXXXXXXXX/FR/XXXXXXXXXXXXXXXXXw8imdmuMKfbgjPCI2XvTXXXXXXXXXXXXXXXXXXeVLTKknTsgGx7xvvXXXXXXXXXXXXXXXXXXXXXXXXXX3191`
Still to setup the key in the application for the service spotify. I think using a dialog to allow user to store these found keys.
Do you think this method could be help or it is too complex for standard user ?

**Comment by marcusklaas** [comment] 2017-01-13 15:41
Wow - thanks for going through all the trouble! I'm seriously impressed and humbled by your dedication.

The process you describe sounds pretty complex. It will be problematic for users without access to a Windows machine as well...

Maybe it's better to wait until more clarity emerges on how other clients like SoCo deal with this and save your time and effort for other features.

**Comment by janbar** [comment] 2017-01-19 16:16
I added a special note about supporting Spotify in the project page: http://janbar.github.io/noson-app/music_services.html

**Comment by janbar** [comment] 2017-01-20 22:22
This issue will be resolved by requesting to relink the app. Then the service response will return the reached "key" we need to refresh the token.

**Comment by janbar** [comment] 2017-01-21 20:18
Fixed with version 2.2.0.
Enter in the service page and launch the registration procedure for each service you want to handle.

**Closed** 2017-01-21 20:19 UTC

**Comment by marcusklaas** [comment] 2017-01-29 17:29
Sweeeet! Will try tonight! 💯

**Comment by janbar** [comment] 2017-01-30 08:05
If you try it on ubuntu phone , the web browser doesn t show the spotify registraion page, maybe due bug or unsupported html. So you have to type the link manually on a desktop web browser. Once registration is confirmed on the linked page, noson will show you the spotify content.
The registration key is saved in noson settings. So you have to do that only one time per device running noson.
I tested the procedure more than 20 times.... hope it will work for you.

**Comment by janbar** [comment] 2017-01-30 08:13
Last friday I closed my free testing account on spotify I subscribed  at the begining of this month.  
I use Deezer instead.
So that's good to know major partners accounts work: spotify, deezer, qobuz

**Comment by janbar** [comment] 2017-01-30 08:17
Last thing since version 2.3.x. I implemented the  media search as you requested. Thanks for your help and your time.
