### ISSUE TITLE
Looks tiny on HiDPI screen running 17.10

### ISSUE THREAD

**Issue by gkjpettet** [janbar/noson-app#19] opened 2017-11-18 07:47 UTC
The window and text are tiny on my HiDPI screen. All other apps are fine. Is there a way to force a scaling factor on the app?

**Comment by janbar** [comment] 2017-11-20 08:47
I guess it should be the snap app because native package is broken since 17.10.
Strange, may be a side effect of snap. The app uses graphic units to be compliant with that. I will try it this morning with a 4k screen.

**Comment by janbar** [comment] 2017-12-13 07:54
Yes the scale factor no longer work with the used sdk (16.04). Currently I am refactoring the app to use the latest Qt framework, and so no longer use the ubuntu sdk. It has been broken since 17.10 and seems being no longer maintained by Canonical.
The good side of the refactoring is the app will be able to run on all platforms supported by Qt.

**Comment by janbar** [comment] 2017-12-26 11:44
I refactored the app for Ubuntu 17.10 and later. No SNAP package is available for this version. You have to install the deb package from my PPA. This version includes the setting for scalling.
A SNAP package could be available once 18.04 is out (April 2018). But you should prefer the native package from my PPA.

**Comment by janbar** [comment] 2017-12-27 10:20
Fixed with version 3.0

**Comment by tomasbulva** [comment] 2018-01-16 15:07
Hi, I have installed the newest version from the PPA on Ubuntu 16.04.3 LTS (Xenial Xerus) HIDPI screen and it looks great but it seems that fonts are not scaling properly:
![2018-01-16-07 00 58-screenshot](https://user-images.githubusercontent.com/2048477/34995491-7de42c52-fa8b-11e7-8ac5-fe2a95b635b5.png)

I tried: 
 export QT_SCALE_FACTOR=2
 export QT_AUTO_SCREEN_SCALE_FACTOR=1
 export QT_STYLE_OVERRIDE=GTK+
 export QT_AUTO_SCREEN_SCALE_FACTOR=1
 export QT_DEVICE_PIXEL_RATIO=auto

...with no success.
any help would be greatly appreciated.

**Comment by janbar** [comment] 2018-01-17 07:22
The new release 3 has its own setting to set the display scale factor. Unfortunately it can be built only since 17.10 because of Qt version.
But I pushed a workaround for the release 2. You have to update the app from the ppa to get the last version 2.5.1 which support a new argument to set the factor in the settings: To store the scale factor you have to start one time the app from the command line with the argument as follows.

    noson --scalefactor=1.2

It will set and store the scale factor in the settings for next run. So to change it again recall the same command line with a new scale factor.

The root cause is a miss in the Ubuntu UI toolkit used by the release 2.

**Comment by janbar** [comment] 2018-01-17 07:24
Fixed now with this workaround

**Closed by janbar** 2018-01-17 07:24 UTC
